# Generated by Django 6.0.3 on 2026-04-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecontent',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
