# Generated by Django 6.0.3 on 2026-04-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('thumb_label', models.CharField(max_length=10)),
                ('thumb_style', models.CharField(choices=[('ct1', 'Blue'), ('ct2', 'Indigo'), ('ct3', 'Teal'), ('ct4', 'Pink')], default='ct1', max_length=5)),
                ('class_type', models.CharField(choices=[('live', 'Live'), ('recorded', 'Recorded')], default='recorded', max_length=10)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_min', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('video_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='course_admin.course')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
