# Generated by Django 6.0.3 on 2026-04-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description shown on the free content listing page.')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF')], help_text='Video = YouTube/embed link.  PDF = direct file URL or Google Drive share link.', max_length=10)),
                ('url', models.URLField(help_text='YouTube link, embed URL, or direct PDF/Drive URL.', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Optional thumbnail image URL (YouTube thumbnail, cover image).', max_length=500)),
                ('duration_min', models.PositiveIntegerField(blank=True, help_text="For videos only — shown as '45m' or '1h 20m' on listing cards.", null=True, verbose_name='Duration (minutes)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive items are hidden from users but kept in the database.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower = shown first in the listing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Leave blank for standalone free content not tied to any course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_content', to='course_admin.course')),
            ],
            options={
                'verbose_name': 'free content item',
                'verbose_name_plural': 'free content items',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
