# Generated by Django 6.0.3 on 2026-04-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('level', models.CharField(choices=[('10th', '10th Level'), ('plus2', '+2 Level'), ('degree', 'Degree Level'), ('special', 'Special Topics'), ('tech', 'Technical'), ('other', 'Others')], max_length=20)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_label', models.CharField(help_text='Shown on thumbnail e.g. PSC', max_length=10)),
                ('sub_label', models.CharField(help_text='Under short_label e.g. Mission SCERT', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('thumb_style', models.CharField(choices=[('thumb1', 'Blue Dark'), ('thumb2', 'Indigo'), ('thumb3', 'Teal'), ('thumb4', 'Pink')], default='thumb1', max_length=10)),
                ('tag_new', models.BooleanField(default=False)),
                ('tag_live', models.BooleanField(default=False)),
                ('tag_free', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course_admin.category')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
