# Generated by Django 6.0.3 on 2026-04-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Main headline. Use | to split into two lines e.g. 'Mission|SCERT PSC 2025'.", max_length=120)),
                ('accent_word', models.CharField(blank=True, help_text='Word inside the title to highlight in yellow. Must match a word in title exactly.', max_length=40)),
                ('subtitle_ml', models.TextField(blank=True, help_text='Displayed in Noto Serif Malayalam below the title.', verbose_name='Subtitle (Malayalam)')),
                ('image', models.ImageField(blank=True, help_text='Optional background image. If omitted, the dark blue gradient is used.', null=True, upload_to='banners/')),
                ('cta_primary', models.CharField(default='Get This Course', max_length=60)),
                ('cta_secondary', models.CharField(blank=True, default='Know More', max_length=60)),
                ('badge_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price shown on the red badge.', max_digits=8, null=True)),
                ('badge_original', models.DecimalField(blank=True, decimal_places=2, help_text='Crossed-out original price on the badge.', max_digits=8, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated chip labels e.g. Live Class,Free Content,Mock Tests', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Only active banners appear in the homepage carousel.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first in the carousel.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text="CTA buttons link to this course's detail page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='course_admin.course')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
